INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (1, 'MEMORY_USAGE', '5000');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (2, 'Metrica_2', '2MB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (3, 'Metrica_3', '12MB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (4, 'Metrica_4', '15MB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (5, 'Metrica_5', '14KB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (6, 'Metrica_6', '40B');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (7, 'Metrica_7', '93MB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (8, 'Metrica_8', '1.2GB');
INSERT INTO METRIC(METRIC_CODE, NAME, VALUE) VALUES (9, 'Metrica_9', '312KB');

INSERT INTO TEAM(TEAM_ID, METRIC_CODE, NAME, DESCRIPTION) VALUES (1, 1, 'Team_MEMORY_USAGE', 2);
INSERT INTO TEAM(TEAM_ID, METRIC_CODE, NAME, DESCRIPTION) VALUES (2, 2, 'Team_B', 4);
INSERT INTO TEAM(TEAM_ID, METRIC_CODE, NAME, DESCRIPTION) VALUES (3, 3, 'Team_C', 5);
INSERT INTO TEAM(TEAM_ID, METRIC_CODE, NAME, DESCRIPTION) VALUES (4, 4, 'Team_D', 8);


INSERT INTO ENGINEER(ENGINEER_ID, TEAM_ID, NAME, EMAIL) VALUES (1,1, 'Brazilinio', 'andre128bits@gmail.com');
INSERT INTO ENGINEER(ENGINEER_ID, TEAM_ID, NAME, EMAIL) VALUES (4,1, 'Anderson', 'anderson.baum@gmail.com');
INSERT INTO ENGINEER(ENGINEER_ID, TEAM_ID, NAME, EMAIL) VALUES (5,1, 'Gustavo', 'gustavohemb93@hotmail.com');
INSERT INTO ENGINEER(ENGINEER_ID, TEAM_ID, NAME, EMAIL) VALUES (2,1, 'Gian', 'andre128bits@hotmail.com');


INSERT INTO SCHEDULE (SCHEDULE_ID, ENGINEER_ID, WEEK_DAY, START_TIME, END_TIME) VALUES (1, 1, 'TERÇA', '00:01:00',  '08:00:00');
INSERT INTO SCHEDULE (SCHEDULE_ID, ENGINEER_ID, WEEK_DAY, START_TIME, END_TIME) VALUES (2, 2, 'TERCA', '08:01:00',  '16:00:00');
INSERT INTO SCHEDULE (SCHEDULE_ID, ENGINEER_ID, WEEK_DAY, START_TIME, END_TIME) VALUES (3, 2, 'TERÇA', '16:01:00',  '00:00:00');
INSERT INTO SCHEDULE (SCHEDULE_ID, ENGINEER_ID, WEEK_DAY, START_TIME, END_TIME) VALUES (4, 4, 'QUARTA', '00:01:00',  '08:00:00');